# Generated by Django 3.2.9 on 2021-11-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211124_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='web_customer',
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='web_subscribe',
        ),
    ]
