# Generated by Django 3.2.9 on 2021-11-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20211124_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='testimonial_logo',
            field=models.FileField(upload_to='features/logos/'),
        ),
    ]
