# Generated by Django 3.2.9 on 2021-11-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_feature_testimonial_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='videoblog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='feature',
            table='web_feature',
        ),
        migrations.AlterModelTable(
            name='testimonial',
            table='web_testimonial',
        ),
        migrations.AlterModelTable(
            name='videoblog',
            table='web_video_blog',
        ),
    ]
