# Generated by Django 3.2.9 on 2021-11-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20211124_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['id']},
        ),
    ]
