# Generated by Django 3.2.9 on 2021-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_testimonial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'web_marketing',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='videoblog',
            options={'ordering': ['id']},
        ),
    ]
