# Generated by Django 3.2.9 on 2021-11-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_marketingfeature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='products/logos/')),
            ],
        ),
    ]
