# Generated by Django 3.2.9 on 2021-11-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='product',
            table='web_products',
        ),
    ]
