# Generated by Django 3.2.9 on 2021-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20211124_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='blogs/')),
                ('title', models.CharField(max_length=128)),
                ('content_type', models.TextField(choices=[('blog_post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')])),
            ],
            options={
                'db_table': 'web_blogs',
                'ordering': ['id'],
            },
        ),
    ]
