# Generated by Django 3.2.9 on 2021-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20211126_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='#ffc9b7', max_length=128),
            preserve_default=False,
        ),
    ]
